server.port: 9000

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/recommend_study?useUnicode=true&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: root
    jedis:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 10
        min-idle: 0
        timeout: 1000


  mail:
    host: smtp.163.com
    username: s15663858182@163.com
    password: NSKKNXURBJDZCPLI
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          starttls.required: true

  mvc:
    view:
      prefix: /jsp/
      suffix: .jsp


mybatis:
  type-handlers-package: com.example.school.study.demo.model
  mapper-locations: classpath:mappers/*.xml

register:
  subject: "线上答题小助手"
  contentV1: "验证码有效时间为2分钟，请您注意把握时间，您的注册验证码为:"
  contentV2: "您之前获取的验证码还未使用，所以本次不会获取新的验证码，请注意过期时间，您的注册码为："

ftp:
  host:
  userName:
  password:
  port:
  rootPath: /usr/local/etc/nginx/video
